
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


/*
 Port1: LiftMotor2 (Can be combined with Prt. 6 in necessity

 Port2: Rear Left Drive

 Port3: Rear Right Drive

 Port4: Intake Motor

 Port5: Front Left Drive

 Port6: Front Right Drive

 Port7: ClawMotor

 Port8: Firing Motors (Splitterx2 + Power Expander)

 Port9: LiftMotor1

Port10: Platform Boost system (?)

*/


task drivetrain(){ //Drivetrain Task. Joshua's code.
	while(true){
		motor[mFR]=(-vexRT[Ch4]+vexRT[Ch3])-vexRT[Ch1];
	  motor[mFL]=(-vexRT[Ch4]-vexRT[Ch3])-vexRT[Ch1];
	  motor[mBL]=(vexRT[Ch4]-vexRT[Ch3])-vexRT[Ch1];
	  motor[mBR]=(vexRT[Ch4]+vexRT[Ch3])-vexRT[Ch1];
	  if(abs(vexRT[Ch4]) < 20 && abs(vexRT[Ch3]) < 20){
	    motor[mFR] = motor[mFL] = motor[mBL] = motor[mBR] = 0;
	  }
	}
}


task ballGrabber(){ //Ball intake system code
	while(true){
		if (vexRT[Btn6U]){
			motor[mGRB] = 127;
	  }else if (vexRT[Btn6D]){
	  	motor[mGRB] = -127;
		} else {
			motor[mGRB] = 0;
		}
	}
}


task go()
{
startTask(drivetrain);
startTask(ballGrabber);

}
