#pragma config(Motor,  port1,           mLFT1,         tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           mBL,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           mBR,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           mGRB,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           mFRE,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           mLFT1,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           mCLW,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           mFR,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           mFL,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          mBST,          tmotorVex393_HBridge, openLoop)
/*
MOTOR CONFIGURATION:
Port1 :Lift Motor 2
Port2 :Rear Left Drive
Port3 :Rear Right Drive
Port4 :Ball Intake
Port5 :Firing Motors
Port6 :Lift Motor 1
Port7 :Claw Motor
Port8 :Front Right Drive
Port9 :Front Left Drive
Port10:Platform Boost System
*/

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true){
		motor[mFR]=(-vexRT[Ch4]+vexRT[Ch3])-vexRT[Ch1];
	  motor[mFL]=(-vexRT[Ch4]-vexRT[Ch3])-vexRT[Ch1];
	  motor[mBL]=(vexRT[Ch4]-vexRT[Ch3])-vexRT[Ch1];
	  motor[mBR]=(vexRT[Ch4]+vexRT[Ch3])-vexRT[Ch1];
	}


}
