
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


/*
 Port1: LiftMotor2 (Can be combined with Prt. 6 in necessity

 Port2: Rear Left Drive

 Port3: Rear Right Drive

 Port4: Intake Motor

 Port5: Front Left Drive

 Port6: Front Right Drive

 Port7: ClawMotor

 Port8: Firing Motors (Splitterx2 + Power Expander)

 Port9: LiftMotor1

Port10: Platform Boost system (?)

*/
int FR;
int FL;
int BR;
int BL;

int mabs(int v){
	return v < 0 ? -v : v;
}

task drivetrain(){ //Drivetrain Task.
	while(true){
		FR=(-vexRT[Ch4]+vexRT[Ch3])-vexRT[Ch1]; //Determines motor speeds. Joshua's Code.
	  FL=(-vexRT[Ch4]-vexRT[Ch3])-vexRT[Ch1];
	  BL=(vexRT[Ch4]-vexRT[Ch3])-vexRT[Ch1];
	  BR=(vexRT[Ch4]+vexRT[Ch3])-vexRT[Ch1];
	  if(mabs(vexRT[Ch4]) < 20 && mabs(vexRT[Ch3]) < 20 && mabs(vexRT[Ch1]) < 20){ //Checks if joystick is in deadzone
	    FR = FL = BR = BL = 0;																									//if so, sets motor speeds to 0
	  }
	  motor[mFR] = FR;  //Applies Motor Speeds
	  motor[mFL] = FL;
	  motor[mBR] = BR;
	  motor[mBL] = BL;
	  EndTimeSlice(); //tells task handler is done
	}
}


task ballGrabber(){ //Ball intake system code
	while(true){
		if (vexRT[Btn6U]){  // if intake button pressed...
			motor[mGRB] = 127; //intake
	  }else if (vexRT[Btn6D]){ //if reverse button pressed
	  	motor[mGRB] = -127; //reverse
		} else {
			motor[mGRB] = 0; //else stop
		}
		EndTimeSlice(); //Tells Task Handler is done
	}
}


void begin() //starts functions
{
startTask(drivetrain);
startTask(ballGrabber);

}
