#pragma config(Sensor, in2,    potClaw,        sensorNone)
#pragma config(Sensor, dgtl1,  LED,            sensorLEDtoVCC)
#pragma config(Sensor, dgtl3,  encLift,        sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  encFR,          sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  encFL,          sensorQuadEncoder)
#pragma config(Sensor, dgtl9,  encBL,          sensorQuadEncoder)
#pragma config(Sensor, dgtl11, encFL,          sensorQuadEncoder)
#pragma config(Motor,  port1,           mFL,           tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           mBL,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           mBR,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           mIntake,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           mLift,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           mFR,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           mClaw,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           mFlyWheelR,    tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           mFlyWheelL,    tmotorVex393HighSpeed_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// potClaw {up: 4096, down: 500}

#pragma platform(VEX2)

#pragma competitionControl(Competition)

#include "Vex_Competition_Includes.c"

#define __DRIVE_SPEED_FACTOR_SLOW 0.5
#define __FLYWHEEL_SECONDARY_SPEED 90


void pre_auton() {
  bStopTasksBetweenModes = true;
}


task autonomous() {
}

// USER CONTROL

task ballIntake () {
	while (true) {
		if (vexRT[Btn5U]) {
			motor[mIntake] = 127;
		} else if (vexRT[Btn5D]) {
			motor[mIntake] = -127;
		} else {
			motor[mIntake] = 0;
		}
		EndTimeSlice();
	}
}

int flyWheelSpeed = 0;
task flyWheel () {
	while (true) {
		motor[mFlyWheel] = flyWheelSpeed;
		if (vexRT[Btn8U]) { // set full speed button pushed
			flyWheelSpeed = 127;
		} else if (vexRT[Btn8L]) { // set secondary speed button pushed
			flyWheelSpeed = __FLYWHEEL_SECONDARY_SPEED;
		} else if (vexRT[Btn8D]) {
			flyWheelSpeed = 0;
		} else if (vexRT[Btn7U]) {
			while (vexRT[Btn7U]) {
				wait1Msec(10);
			}
			flyWheelSpeed += 10;
			flyWheelSpeed = flyWheelSpeed > 127 ? 127 : flyWheelSpeed;
		} else if (vexRT[Btn7R]) {
			while (vexRT[Btn7R]) {
				wait1Msec(10);
			}
			flyWheelSpeed -= 10;
			flyWheelSpeed = flyWheelSpeed < 0 ? 0 : flyWheelSpeed;
		}
		EndTimeSlice();
	}
}
/*
task lifter () { // task controlling the cascade-lift an the claw
	while (true) {
		if (vexRT[Btn6U]) { // if the lift mode is active (when right trigger or Btn6U is pushed)
			if (vexRT[Btn5U]) {
				motor[mLift1]

		EndTimeSlice();
	}
}
	*/

float fmax (float a, float b) {
	return a > b ? a : b;
}

float ms[4]; // Motor Speeds 0: FL, 1: FR, 2: BL, 3: BR
float driveFactor = 1.0;
task drive() {
  float maxMotor, targetRatio;
  int i;
	while (true) {
		if (vexRT[Btn6U]) { // if the acceleration button is pressed...
			driveFactor = 1.0;
		} else {
			driveFactor = __DRIVE_SPEED_FACTOR_SLOW;
		}
    // Death zones
		if (abs(vexRT[Ch4]) < 20 && abs(vexRT[Ch3]) < 20 && abs(vexRT[Ch1]) < 20) {
			ms[0] = ms[1] = ms[2] = ms[3] = 0;
		} else {
			ms[0] = -vexRT[Ch4] - vexRT[Ch3] - vexRT[Ch1];
			ms[1] = -vexRT[Ch4] + vexRT[Ch3] - vexRT[Ch1];
			ms[2] =  vexRT[Ch4] - vexRT[Ch3] - vexRT[Ch1];
			ms[3] =  vexRT[Ch4] + vexRT[Ch3] - vexRT[Ch1];
		}
		// Make sure at least one of the motors is running at full spead
		maxMotor = ms[0];
		for (i = 1; i < 4; ++i) {
			maxMotor = fmax (ms[i], maxMotor);
		}
		targetRatio = 127.0 / maxMotor;
		for (i = 0; i < 4; ++i) {
			ms[i] *= targetRatio;
		}

    // Set each motor to a target speed
		motor[mFL] = ms[0] * driveFactor;
		motor[mFR] = ms[1] * driveFactor;
		motor[mBL] = ms[2] * driveFactor;
		motor[mBR] = ms[3] * driveFactor;
		EndTimeSlice();
	}
}

task usercontrol() {
	startTask(drive);
	startTask(ballIntake);
	startTask(flyWheel);
  while (true) {
    EndTimeSlice();
  }
}
